<?php

$DB_GEN_HOST = $CONFIG['DB_GEN']['HOST'];
$DB_GEN_USER = $CONFIG['DB_GEN']['USER'];
$DB_GEN_PASS = $CONFIG['DB_GEN']['PASS'];
$DB_BATCH_NAME = $CONFIG['DB_GEN']['BATCH_NAME'];

$SQL = new mysqli($DB_GEN_HOST, $DB_GEN_USER, $DB_GEN_PASS, $DB_BATCH_NAME);
